name: Docker Image CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.18'
    - name: Run build
      run: make
    - name: Set version env
      run: echo "CI_VERSION=$(cat VERSION | awk NF)" >> $GITHUB_ENV
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ env.CI_VERSION }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.CI_VERSION }}
        name: ${{ env.CI_VERSION }}
        artifacts: "build/onedrive-uploader_*"

    