name: release

on:
  workflow_dispatch:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.22'
    - name: Run build
      run: make
    - name: Set version env
      run: echo "CI_VERSION=$(cat VERSION | awk NF)" >> $GITHUB_ENV
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.CI_VERSION }}
        name: ${{ env.CI_VERSION }}
        artifacts: "build/onedrive-uploader_*"