name: test

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.22'
    - name: Create config.json
      id: create-json-config
      uses: jsdaniell/create-json@1.2.3
      with:
        name: "config.json"
        json: ${{ secrets.CONFIG_JSON }}
    - name: Run tests on main
      run: go test -cover -v
      env:
        CGO_ENABLED: 0
    - name: Run tests on SDK
      working-directory: ./sdk
      run: go test -cover -v
      env:
        CGO_ENABLED: 0
    - name: Run build
      run: make