name: test

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.19'
    - name: Create config.json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "config.json"
        json: ${{ secrets.CONFIG_JSON }}
    - name: Create secret.json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "secret.json"
        json: ${{ secrets.SECRET_JSON }}
    - name: Run tests on main
      run: go test -cover -v
      env:
        CGO_ENABLED: 0
    - name: Run tests on SDK
      working-directory: ./sdk
      run: go test -cover -v
      env:
        CGO_ENABLED: 0
    - name: Run build
      run: make